socket:
  host: 192.168.1.60
  port: 10001
  reconnect_interval: 5  # seconds

mqtt:
  broker: 192.168.1.87
  port: 1883
  topic_sub: homeassistant
  topic_state_pub: inovonics
  topic_pub: homeassistant
  client_id: MySocketMQTTClient
  username: "mqtt"  # Optional
  password: "H6V2L3N2"  # Optional
  reconnect_interval: 5  # seconds

logging:
  file: "app.log"
  level: "INFO"
